### ISSUE TITLE
Work on all features

### ISSUE THREAD

**Issue by banivyom** [mondejar/ecg_classification_tf#10]
Actually, I want to work on all 180 features rather than extracting few of them(wvlt, HOS, etc)
So is there a way to do that?
Thanks.

**Comment by mondejar** [comment]
Check the file _run_train_SVM.py_. In that file, you can set in the variable `compute_morph = {''}` the desired computed features. Additionally, in order to use the raw signal, just set `compute_morph = {'raw'}`. In the file _load_MITBIH.py_ is considered that option. You are also free to compute your own features

**Comment by banivyom** [comment]
use_RR = False
norm_RR = False
compute_morph = {'raw'}
So here I should use use_RR = False and norm_RR = False right?

**Comment by mondejar** [comment]
Yes, in order to just employ the raw signal is correct as you said. You can also adjust the desired windows size with `winL` and `winR` when you call the `main` method.

**Comment by banivyom** [comment]
Thanks, changed the window size to 180 each few days ago :-D
